# CPU-GPU implementation
(The log of device can be seen on terminal)

In [1]:
import tensorflow as tf

### Checking cpu or gpu usage:

In [10]:
# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)

In [22]:
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [16]:
# Runs the op.
print(sess.run(c))

[[ 22.  28.]
 [ 49.  64.]]


### Forcing CPU

In [24]:
# Creates a graph.
with tf.device('/cpu:0'):
    cpu_a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    cpu_b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    cpu_c = tf.matmul(a, b)


In [26]:
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))


In [27]:
# Runs the op.
sess.run(cpu_c)

array([[ 22.,  28.],
       [ 49.,  64.]], dtype=float32)

### Forcing GPU

In [21]:
# Creates a graph.
with tf.device('/gpu:0'):
    gpu_a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    gpu_b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    gpu_c = tf.matmul(a, b)


In [23]:
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [20]:
# Runs the op.
sess.run(gpu_c)

array([[ 22.,  28.],
       [ 49.,  64.]], dtype=float32)