# CPU-GPU implementation
(The log of device can be seen on terminal)

In [1]:
import tensorflow as tf

### Checking cpu or gpu usage:

In [2]:
# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)

In [3]:
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [4]:
# Runs the op.
print(sess.run(c))

[[ 22.  28.]
 [ 49.  64.]]


### Forcing CPU

In [5]:
# Creates a graph.
with tf.device('/cpu:0'):
    cpu_a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    cpu_b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    cpu_c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))


In [6]:
# Runs the op.
sess.run(cpu_c)

array([[ 22.,  28.],
       [ 49.,  64.]], dtype=float32)

### Forcing GPU

In [7]:
# Creates a graph.
with tf.device('/cpu:0'):
    gpu_a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    gpu_b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    gpu_c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [8]:
# Runs the op.
sess.run(gpu_c)

array([[ 22.,  28.],
       [ 49.,  64.]], dtype=float32)